src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): static
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class UserController extends AbstractController
{
    #[Route('admin/user', name: 'app_user')]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }
    #[Route('/admin/user/{id}/to/editor', name: 'app_user_to_editor')]
    public function changeRole(EntityManagerInterface $entityManager, User $user): Response
    {
        $user->setRoles(["ROLE_USER", "ROLE_EDITOR"]);
        $entityManager->flush();
        $this->addFlash("success", "Role editeur ajouté a l'utilisateur");
        return $this->redirectToRoute('app_user');


    }
    #[Route('/admin/user/{id}/remove/editor/role', name: 'app_user_remove_editor_role')]
    public function editorRoleRemove(EntityManagerInterface $entityManager, User $user): Response
    {
        $user->setRoles([]);
        $entityManager->flush();
        $this->addFlash("danger", "Role editeur retiré de l'utilisateur");
        return $this->redirectToRoute('app_user');


    }
    #[Route('/admin/user/{id}/remove/', name: 'app_user_remove')]
    public function userRemove(EntityManagerInterface $entityManager,$id, UserRepository $userRepository): Response
    {
        $userFind= $userRepository->find($id);
        $entityManager->remove($userFind);
        $entityManager->flush();
        $this->addFlash("danger", "utilisateur supprimé");
        return $this->redirectToRoute('app_user');


    }

}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs!{% endblock %}

{% block body %}
<div class="container">
    <br><br><br>
    <h1>Utilisateurs</h1><br><br><br>

    {% include 'layout/_flash_message.html.twig' %}

    <table class="table">
    <tr>
        <th>id</th>
        <th>email</th>
        <th>nom</th>
        <th>Prenom</th>
        <th>role</th>
        <th>action</th>
    </tr>
      {% for user in users%}
        <tr>
            <td>
                {{ user.id }}
            </td>
            <td>
                {{  user.email}}
            </td>
            <td>
                {{  user.firstName}}
            </td>
            <td>
                {{  user.lastName}}
            </td>
            <td>
            {% if('ROLE_ADMIN' in user.roles) %}
                <span class="text-primary">administrateur <span>
            {% elseif ('ROLE_EDITOR' in user.roles) %}
                <span class="text-success" >editeur <span>
            {% else%}
                <span class="text-secondary">client</span>
            {% endif %}


               {# {%for role in user.roles%}
                    {{ role }}
                {% endfor %}
            </td>#}
            <td>
                {% if ('ROLE_ADMIN' in user.roles)== false %}
                    {% if ('ROLE_EDITOR' in user.roles)== false %}
                        <a onclick="return confirm('voulez-vous vraiment affecter le role éditeur à cet utilisateur?')" class="btn btn-outline-primary" href="{{ path('app_user_to_editor',{'id':user.id}) }}">Ajouter comme éditeur </a>
                    {% else %}
                        <a onclick="return confirm('voulez-vous vraiment retirer le role éditeur à cet utilisateur?')" class="btn btn-danger" href="{{ path('app_user_remove_editor_role',{'id':user.id}) }}">retirer le role éditeur </a>
                    {% endif %}




                    <a     <a onclick="return confirm('voulez-vous vraiment supprimer cet utilisateur?')" href="{{ path('app_user_remove',{id: user.id}) }}" class="btn btn-danger">Supprimer</a>

                {% endif %}

            </td>

        </tr>
      {% endfor%}
    </table>

</div>

{% endblock %}